### ISSUE TITLE
KeyError: 'X' when processing test data 

### ISSUE THREAD

**Issue by lowel0** [ku-cbd/PhageBoost#18]
Hi,

I have successfully install PhageBoost 1.3.1 using the pip install PhageBoost and been unable to successfully process the NC_000907.fasta.gz test data.  I get the following error output:

> PhageBoost -f NC_000907.fasta.gz -o results
> processing: NC_000907
> time after genecalls: 4.93197774887085
> Traceback (most recent call last):
>   File "/home/lowel/.local/bin/PhageBoost", line 8, in <module>
>     sys.exit(main())
>   File "/home/lowel/.local/lib/python3.9/site-packages/PhageBoost/main.py", line 219, in main
>     df = calculate_features(genecalls)
>   File "/home/lowel/.local/lib/python3.9/site-packages/PhageBoost/main.py", line 59, in calculate_features
>     df, _, _ = calc_features.df2AAandDNAfeatures(genecalls, name='header')
>   File "/home/lowel/.local/lib/python3.9/site-packages/PhageBoost/calc_features.py", line 215, in df2AAandDNAfeatures
>     DF, DF_AA, DF_DNA = RunAAandDNA(dna_entries, aa_entries, locations)
>   File "/home/lowel/.local/lib/python3.9/site-packages/PhageBoost/calc_features.py", line 202, in RunAAandDNA
>     DF_AA = RunAA(AA_entries, verbose = verbose)
>   File "/home/lowel/.local/lib/python3.9/site-packages/PhageBoost/calc_features.py", line 178, in RunAA
>     df_biopython = biopython_proteinanalysis(entries, scaling=scaling)
>   File "/home/lowel/.local/lib/python3.9/site-packages/PhageBoost/calc_features.py", line 168, in biopython_proteinanalysis
>     d = biopython_proteinanalysis_seq(seq, scaling=scaling)
>   File "/home/lowel/.local/lib/python3.9/site-packages/PhageBoost/calc_features.py", line 33, in biopython_proteinanalysis_seq
>     flex = np.array(res.flexibility())
>   File "/home/lowel/.local/lib/python3.9/site-packages/Bio/SeqUtils/ProtParam.py", line 183, in flexibility
>     score += (flexibilities[front] + flexibilities[back]) * weights[j]
> KeyError: 'X'
> 

I am using xgboost==1.1.1, but have used various permutations of python, PhageBoost and xgboost versions to no avail.

Can anybody please help with this?

Sincere regards,

**Comment by tsp-kucbd** [comment]
I cannot reproduce this error, but it seems something is happening inside Biopython. Can you show us which Biopython version you are using?
`import Bio`
`print(Bio.__version__)`

**Comment by WuJiaWei121** [comment]
> 我无法重现此错误，但 Biopython 内部似乎发生了一些事情。您能告诉我们您使用的是哪个 Biopython 版本吗？
> `import Bio`
> `print(Bio.__version__)`

I also encountered the above problems.
My bio version is 1.79.
How should I solve this problem?

**Comment by lowel0** [comment]
Hi,

> I cannot reproduce this error, but it seems something is happening inside Biopython. Can you show us which Biopython version you are using?
> `import Bio`
> `print(Bio.__version__)`

My Bio version is also 1.79.

Sincere regards,

...Lowel.

**Comment by tsp-kucbd** [comment]
I reinstalled it on a new machine and could reproduce it, it seems pyrodigal has changed its internals. You can use the git hub version for now, until we create a new pip package.

**Comment by lowel0** [comment]
Hi,

Thank you for the quick investigation.  I have used the "github" installation with xgboost==1.1.1 and can now succussfully process the test data.

Sincere regards,

...Lowel.

**Comment by WuJiaWei121** [comment]
> 
Hi,
I don't understand the meaning of that "I have used the "github" installation with xgboost==1.1.1". Could you help explain it?

**Comment by lowel0** [comment]
Hi,
As part of the install process you use pip to install xgboost.  By default the working version was not being installed, but this was corrected by using the command:

pip install xgboost==1.1.1

Sincere regards,
...Lowel.

**Comment by WuJiaWei121** [comment]
Hi
Thank you for your response. I have used pip to install xgboost==1.1.1 successfully, but it still seems to make the same mistake :
KeyError: 'X' when processing test data

what's more ,I tried to replace the cal_ Features.py file, but it still doesn't seem to work. Could you have some good tips?

**Comment by lowel0** [comment]
Hi,

I managed to get rid of the error by using python 3.7.0 and the development
version from github rather than using the released version:

git clone https://github.com/ku-cbd/PhageBoost.git
cd PhageBoost
python setup.py bdist_wheel
pip install . xgboost==1.1.1

The python version is important.

Sincere regards,

...Lowel.
